version: "2"
services:
  fuseki:
    image: atomgraph/fuseki
    ports:
      - 3030:3030
    volumes:
      - ./config/ds.ttl:/mnt/apache-fuseki/configuration/ds.ttl:ro
    command: ["--config", "/mnt/apache-fuseki/configuration/ds.ttl"]
  fuseki-write:
    image: atomgraph/fuseki
    ports:
      - 3031:3030
    volumes:
      - ./config/ds.ttl:/mnt/apache-fuseki/configuration/ds.ttl:ro
    command: ["--config", "/mnt/apache-fuseki/configuration/ds.ttl"]
  processor-ct:
    image: atomgraph/processor
    depends_on:
      - fuseki
    ports:
      - 8080:8080
      - 8002:8000 # debugger
    environment:
      - JPDA_ADDRESS=*:8000 # debugger port
      - ENDPOINT="http://fuseki:3030/ds/" # hostname equals service name
      - GRAPH_STORE="http://fuseki:3030/ds/" # hostname equals service name
      - ONTOLOGY="https://www.w3.org/ns/ldt/core/templates#"
  processor-ct-write: # dataset will be modified
    image: atomgraph/processor
    depends_on:
      - fuseki-write
    ports:
      - 8081:8080
      - 8003:8000 # debugger
    environment:
      - JPDA_ADDRESS=*:8000 # debugger port
      - ENDPOINT="http://fuseki-write:3030/ds/" # hostname equals service name
      - GRAPH_STORE="http://fuseki-write:3030/ds/" # hostname equals service name
      - ONTOLOGY="https://www.w3.org/ns/ldt/core/templates#"
  processor-ngt:
    image: atomgraph/processor
    depends_on:
      - fuseki
    ports:
      - 8082:8080
      - 8004:8000 # debugger
    environment:
      - JPDA_ADDRESS=*:8000 # debugger port
      - ENDPOINT="http://fuseki:3030/ds/" # hostname equals service name
      - GRAPH_STORE="http://fuseki:3030/ds/" # hostname equals service name
      - ONTOLOGY="https://www.w3.org/ns/ldt/named-graphs/templates#"
  processor-ngt-write: # dataset will be modified
    image: atomgraph/processor
    depends_on:
      - fuseki-write
    ports:
      - 8083:8080
      - 8005:8000 # debugger
    environment:
      - JPDA_ADDRESS=*:8000 # debugger port
      - ENDPOINT="http://fuseki-write:3030/ds/" # hostname equals service name
      - GRAPH_STORE="http://fuseki-write:3030/ds/" # hostname equals service name
      - ONTOLOGY="https://www.w3.org/ns/ldt/named-graphs/templates#"
  processor-custom:
    image: atomgraph/processor
    depends_on:
      - fuseki
    ports:
      - 8085:8080
      - 8006:8000 # debugger
    environment:
      - JPDA_ADDRESS=*:8000 # debugger port
      - ENDPOINT="http://fuseki:3030/ds/" # hostname equals service name
      - GRAPH_STORE="http://fuseki:3030/ds/" # hostname equals service name
      - ONTOLOGY="https://github.com/AtomGraph/Processor/blob/develop/http-tests/custom#"
    volumes:
      - ./linked-data-templates/custom/ontology.ttl:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/com/atomgraph/processor/http-tests/custom/ontology.ttl:ro
      - ./linked-data-templates/custom/location-mapping.n3:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/custom-mapping.n3:ro
  processor-custom-write:
    image: atomgraph/processor
    depends_on:
      - fuseki-write
    ports:
      - 8086:8080
      - 8007:8000 # debugger
    environment:
      - JPDA_ADDRESS=*:8000 # debugger port
      - ENDPOINT="http://fuseki-write:3030/ds/" # hostname equals service name
      - GRAPH_STORE="http://fuseki-write:3030/ds/" # hostname equals service name
      - ONTOLOGY="https://github.com/AtomGraph/Processor/blob/develop/http-tests/custom#"
    volumes:
      - ./linked-data-templates/custom/ontology.ttl:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/com/atomgraph/processor/http-tests/custom/ontology.ttl:ro
      - ./linked-data-templates/custom/location-mapping.n3:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/custom-mapping.n3:ro