language: c
before_install:
 - sudo apt-get update
 - sudo apt-get install -qq raptor2-utils

before_script:
 - cd http-tests
 - docker-compose pull
 - docker-compose up -d

env:

script:
  -  bash ./run.sh

notifications:
  email:
    recipients:
      - martynas@atomgraph.com