language: c
before_install:
  - sudo apt-get update
  - sudo apt-get install -qq raptor2-utils

install:
  - cd http-tests
  - docker-compose pull
  - docker-compose up -d # run fuseki and processor in the background

before_script:
  - while ! curl -w "%{http_code}\n" -s http://localhost:8080 | grep "200" ; do sleep 1 ; done # wait for processor-ct to start
  - while ! curl -w "%{http_code}\n" -s http://localhost:8081 | grep "200" ; do sleep 1 ; done # wait for processor-ct-write to start
  - while ! curl -w "%{http_code}\n" -s http://localhost:8082 | grep "200" ; do sleep 1 ; done # wait for processor-ngt to start
  - while ! curl -w "%{http_code}\n" -s http://localhost:8083 | grep "200" ; do sleep 1 ; done # wait for processor-ngt-write to start

script:
  -  bash ./run.sh # run tests

after_script:
  - docker-compose down # shutdown fuseki and processor
  - docker-compose rm -f

notifications:
  email:
    recipients:
      - martynas@atomgraph.com