language: c
before_install:
 - sudo apt-get update
 - sudo apt-get install -qq raptor2-utils

install:
 - cd http-tests
 - docker-compose pull
 - docker-compose up -d

env:

before_script:
#  - curl http://localhost:8080/
#  - curl http://localhost:8081/
  - docker ps

script:
  -  bash ./run.sh

after_script:
  - docker-compose down
  - docker-compose rm -f

notifications:
  email:
    recipients:
      - martynas@atomgraph.com