version: "2"
services:
  processor:
    image: atomgraph/processor
    ports:
      - 8080:8080
      - 8010:8000 # debugger
    environment:
      - JPDA_ADDRESS=*:8000 # debugger port
      - ENDPOINT="https://query.wikidata.org/bigdata/namespace/wdq/sparql"
      - GRAPH_STORE="https://query.wikidata.org/bigdata/namespace/wdq/service" # fake value, unused
      - ONTOLOGY="https://github.com/AtomGraph/Processor/blob/develop/examples/wikidata#"
    volumes:
      - ./wikidata.ttl:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/org/wikidata/ldt.ttl
      - ./location-mapping.n3:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/custom-mapping.n3